"""
File Name: test_chat.py
Purpose: Tests that our Chatbot/RAG Pipeline correctly understands user intent.
Why it exists: We need to make sure that "give me a hint for 1500A" actually triggers 
the HintEngine, and doesn't just do a random search.
What it imports: unittest, src.rag_pipeline.RAGPipeline
Role in pipeline: Validation layer.
"""

import unittest
from unittest.mock import MagicMock
from src.rag_pipeline import RAGPipeline
import pandas as pd

class TestRAGPipeline(unittest.TestCase):
    def setUp(self):
        """
        Runs before every single test.
        Since loading the real SentenceTransformer takes time, we 'Mock' (fake) the recommender.
        """
        # Create a fake dataframe that the RAG pipeline can search against
        fake_data = pd.DataFrame([{
            'id': 1, 'contest_id': 1500, 'problem_index': 'A',
            'name': 'Fake Problem', 'difficulty': 1000, 
            'tags': 'math', 'statement_summary': 'Do some addition.'
        }])
        
        # Create a Fake recommender object
        self.mock_recommender = MagicMock()
        self.mock_recommender.df = fake_data
        
        # Initialize RAG with the fake recommender
        self.rag = RAGPipeline(self.mock_recommender)

    def test_hint_intent(self):
        """
        Validates that asking for a hint returns a string containing the word HINT.
        """
        response = self.rag.process_query("give me a hint for 1500A")
        self.assertIn("HINT generated by", response)
        
    def test_summary_intent(self):
        """
        Validates that asking for a summary returns a string containing Editorial.
        """
        response = self.rag.process_query("Summarize 1500A")
        self.assertIn("Editorial Summary for", response)

if __name__ == '__main__':
    unittest.main()
