"""
File Name: hint_engine.py
Purpose: Generates safe, non-spoilery educational hints for Codeforces problems.
Why it exists: A core feature of the app is "contextual hints". If a user is stuck, 
we shouldn't give them the answer (which ruins the learning). We should give them a nudge.
What it imports: None.
Which files use it: rag_pipeline.py, chatbot.py
Inputs: Problem tags, problem difficulty, and an optional problem summary.
Outputs: A string containing a generated hint.
Role in pipeline: Supporting utility for the Chatbot / RAG module.

Simplification Note:
In a highly advanced project, we would finetune an LLM on competitive programming editorials 
to generate step-by-step hints. For this student-level project, we use a heuristic 
Template-Based Hint System. It looks at the tags and difficulty and selects appropriate 
teaching strategies.
"""

# ==========================================
# BUILT-IN PYTHON LIBRARIES
# ==========================================
import random # Standard library used here to pick a random hint from our template arrays, adding variety to the bot.

def generate_hint(tags: str, difficulty: int = None, problem_name: str = "This problem") -> str:
    """
    Looks at a problem's tags and difficulty and returns a pre-written template hint.
    
    What it does:
    It checks if the tags contain certain keywords (like 'dp', 'graphs') and selects a 
    random, relevant hint template that guides the user towards the right state of mind.
    
    Why it exists: Without an expensive, slow API call to GPT-4, this is the safest and 
    fastest way to give a student a guaranteed "non-spoiler" hint.
    
    Where it is used: When a user types "hint 1500A" in the API/Chatbot.
    """
    
    if not tags:
        return f"For {problem_name}, since there are no clear tags, start by writing out a small example by hand. Can you solve it for n=1, 2, and 3?"
        
    tags_lower = str(tags).lower()
    
    hints = []
    
    # Heuristics based on common Codeforces tags
    if 'dp' in tags_lower:
        hints.append("This involves Dynamic Programming. Ask yourself: what is the 'state' you need to keep track of at step 'i'?")
        hints.append("Can you express the answer for N using the answers calculated for N-1 or N-2?")
        
    if 'graphs' in tags_lower or 'trees' in tags_lower:
        hints.append("Try modeling this as a graph. What are the nodes and what are the edges?")
        hints.append("Would a simple BFS or DFS help you explore the state space here?")
        
    if 'math' in tags_lower or 'number theory' in tags_lower:
        hints.append("Write out the first 5 examples on paper. Do you notice a mathematical pattern or cycle?")
        hints.append("Is there a way to simplify the algebraic equation before writing loops in your code?")
        
    if 'greedy' in tags_lower:
        hints.append("This is a greedy problem. What is the absolute 'best' local choice you can make at each step?")
        hints.append("Try to sort the input first. Does processing it in a specific order make the greedy choice obvious?")
        
    # If we matched some specific tags, return one of those hints randomly
    if hints:
        hint = random.choice(hints)
    else:
        # Generic fallback hint
        hint = f"Focus on the constraints. Can you afford an O(N^2) solution, or must it be O(N log N)? Identify the bottlenecks."
        
    return f"[HINT generated by HintEngine]: {hint}"
